name: Build Resumes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04 # Explicitly use ubuntu-22.04; change to ubuntu-24.04 when ready

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Resumes
      run: python scripts/build.py

    - name: Upload Build Directory
      uses: actions/upload-artifact@v4
      with:
        name: resume-builds
        path: builds/
