name: Build Resumes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Install Python Dependencies
      run: pip install json

    - name: Build Resumes
      run: python scripts/build.py

    - name: Upload Build Directory
      uses: actions/upload-artifact@v3
      with:
        name: resume-builds
        path: build/
